name: Build OutlookHelperServer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained exe
        run: dotnet publish OutlookHelperServer.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o out

      - name: List published files
        run: dir out

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: OutlookHelperServer
          path: out/OutlookHelperServer.exe
