name: Build Windows EXE

on:
  push:
    branches: [ "main" ]  # ou "master" selon ton repo

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Publish self-contained (win-x64)
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: outlook-helper-server
	path: out/*
